##################################################
# Generated by phansible.com
##################################################

#If your Vagrant version is lower than 1.5, you can still use this provisioning
#by commenting or removing the line below and providing the config.vm.box_url parameter,
#if it's not already defined in this Vagrantfile. Keep in mind that you won't be able
#to use the Vagrant Cloud and other newer Vagrant features.
Vagrant.require_version ">= 1.5"

# Check to determine whether we're on a windows or linux/os-x host,
# later on we use this to launch ansible in the supported way
# source: https://stackoverflow.com/questions/2108727/which-in-ruby-checking-if-program-exists-in-path-from-ruby
def which(cmd)
    exts = ENV['PATHEXT'] ? ENV['PATHEXT'].split(';') : ['']
    ENV['PATH'].split(File::PATH_SEPARATOR).each do |path|
        exts.each { |ext|
            exe = File.join(path, "#{cmd}#{ext}")
            return exe if File.executable? exe
        }
    end
    return nil
end


Vagrant.configure("2") do |config|

    _hostName = "ahoi.glueckskind.hamburg"
    config.vm.provider :virtualbox do |v|
        v.name = _hostName
        v.customize [
            "modifyvm", :id,
            "--name", _hostName,
            "--memory", 1024,
            "--natdnshostresolver1", "on",
            "--cpus", 2,
        ]
    end

    config.vm.hostname = _hostName

    config.vm.box = "ubuntu/trusty64"

    config.vm.network :private_network, ip: "192.168.56.126"
    config.ssh.forward_agent = true

    config.vm.provision :shell, path: "ansible/windows.sh", args: ["symfony.dev"]

    config.vm.synced_folder "./", "/vagrant", type: "nfs", mount_options: ['actimeo=2']

    # Hostmanager adds the VM hostname to your hosts file
    if Vagrant.has_plugin?("vagrant-hostmanager")
        config.hostmanager.enabled = true
        config.hostmanager.manage_host = true
        config.hostmanager.ignore_private_ip = false
        config.hostmanager.include_offline = true
        config.hostmanager.aliases = %w(ahoi.html.glueckskind.hamburg)
    end
end
